#!/usr/bin/env python3
"""Step 13 — write the hero storyboard markup into index.html.

THE RE-SWAP, when more `finwy3d-act-NN-vNN.png` land in `incoming/`:

    cd <worktree>/assets/finwy-3d
    python3 src/10-hero-action.py     # matte + register + encode + manifest
    python3 src/13-hero-markup.py     # rewrite index.html from the manifest

Nothing else. The script owns three things in index.html and touches nothing
else:

  * everything between `<!-- HERO-FRAMES:BEGIN -->` and `<!-- HERO-FRAMES:END -->`
  * the `--hero-aspect:` declaration on `.hero__mascot` (the registration
    canvas grows if a new keyframe reaches further than the old union bbox)
  * the `<img>` `width`/`height` attributes, same reason

It is idempotent, and it refuses to run if the markers are missing rather than
guessing where the block goes.
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SITE = ROOT.parents[1]                       # the worktree root
INDEX = SITE / "index.html"
SIZES = "(max-width: 700px) 204px, 360px"    # phone slot, desktop slot
EAGER = 2                                    # first N frames load eagerly

m = json.loads((ROOT / "hero" / "manifest.json").read_text())
W, H = m["canvas"]
widths = m["widths"]
frames, settle = m["frames"], m["settle"]


def srcset(files, ext):
    return ", ".join(f"{files[f'{w}{ext}']} {w}w" for w in widths)


out = []
a = out.append
a('            <!-- HERO-FRAMES:BEGIN — generated by src/13-hero-markup.py from')
a('                 assets/finwy-3d/hero/manifest.json. Do not hand-edit: run')
a('                 10-hero-action.py then 13-hero-markup.py.')
a('')
a("                 The founder's storyboard is eight keyframes — asleep, lifting,")
a('                 arms-up grin, leaning wave, mid-spin, jump, landing, the winking')
a(f'                 "Hi". {len(frames)} of 8 exist right now and the build consumed exactly')
a('                 those; the rest fall back by simply not being in the list, and')
a('                 the run re-times itself around whatever count it has.')
a('')
a(f'                 Every frame is re-anchored on one shared {W}x{H} canvas (ground')
a('                 line + body axis) because each generation frames the character')
a('                 differently — played raw the character sank ~80px between')
a('                 keyframes. That shared canvas is also why the settled pose can')
a('                 cross-fade over the last action frame without a jump.')
a('')
a('                 FALLBACK: if zero act-NN frames exist, 10-hero-action.py says so')
a('                 and the 15-frame deck flipbook (fw-deck-2026/slides/frame-N-409w.*)')
a('                 is what belongs here instead. It is not in the DOM while these are —')
a('                 15 dead <img> tags is 15 dead requests. -->')
for i, f in enumerate(frames, start=1):
    fl = f["files"]
    a('            <picture>')
    a(f'              <source type="image/avif" srcset="{srcset(fl, "avif")}" sizes="{SIZES}">')
    a(f'              <img src="{fl[f"{widths[0]}webp"]}"')
    a(f'                   srcset="{srcset(fl, "webp")}" sizes="{SIZES}"')
    a(f'                   class="{"is-active" if i == 1 else ""}" data-frame="{i}" data-act="{f["key"]}"'
      f' data-src-render="{f["source"]}" alt=""')
    a(f'                   width="{W}" height="{H}" loading="{"eager" if i <= EAGER else "lazy"}"'
      f'{" fetchpriority=&quot;high&quot;" if i == 1 else ""} decoding="async">'
      .replace("&quot;", '"'))
    a('            </picture>')
fl = settle["files"]
a('            <!-- The SETTLED pose — what the reader looks at for the 99% of the')
a('                 visit that is not the wake-up, so it is the frame that has to be')
a('                 the good one. Build preference: act-08 (the winking "Hi") >')
a(f'                 hero-wave-energetic > wave-v04. Currently {settle["source"]}. -->')
a('            <picture>')
a(f'              <source type="image/avif" srcset="{srcset(fl, "avif")}" sizes="{SIZES}">')
a('              <img class="hero__mascot-settled" id="hero-mascot-settled"')
a(f'                   src="{fl[f"{widths[0]}webp"]}"')
a(f'                   srcset="{srcset(fl, "webp")}" sizes="{SIZES}"')
a(f'                   data-src-render="{settle["source"]}"')
a(f'                   width="{W}" height="{H}" alt="" loading="eager" decoding="async">')
a('            </picture>')
a('            <!-- HERO-FRAMES:END -->')
block = "\n".join(out) + "\n"

s = INDEX.read_text()
b = "            <!-- HERO-FRAMES:BEGIN"
e = "            <!-- HERO-FRAMES:END -->\n"
if b not in s or e not in s:
    raise SystemExit(
        "HERO-FRAMES markers not found in index.html — refusing to guess. "
        "Restore them around the #hero-mascot <picture> stack first.")
i, j = s.index(b), s.index(e) + len(e)
s = s[:i] + block + s[j:]

# the registration canvas can grow when a new keyframe extends the union bbox
s = re.sub(r"--hero-aspect: [\d.]+ / [\d.]+;", f"--hero-aspect: {W} / {H};", s)

INDEX.write_text(s)
print(f"index.html: {len(frames)} action frames + settle, canvas {W}x{H} "
      f"(aspect {W/H:.4f}), tiers {widths}")
print(f"  frames: {[f['key'] + ' <- ' + f['source'] for f in frames]}")
print(f"  settle: {settle['source']}")
